title: Winnow Design System
email: your-email@example.com
description: >-
  Examples here are meant for communicating responsive designs to Winnow development teams.
baseurl: ""
url: ""
twitter_username: jekyllrb
github_username: jekyll

disable_disk_cache: true

theme: minima
plugins:
  - jekyll-feed
